services:
  app:
    # buildコンテキストとしてカレントディレクトリ(.)を指定し、Dockerfileを探す
    build: .
    # コンテナに分かりやすい名前をつける
    container_name: secure_checker_app
    # .envファイルから環境変数を読み込ませる
    env_file:
      - .env
      #鯖側にDBを作成(消えない)
    volumes:
      - ./data:/app/data

  nginx:
    # Docker Hubから公式の最新Nginxイメージを取得
    image: nginx:latest
    container_name: secure_checker_nginx
    ports:
      - "80:80"   # HTTP用の80番ポート
      - "443:443" # HTTPS用の443番ポート
    # nginx.confを、コンテナ内のNginxの設定ファイルとして使用する
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # SSL証明書をマウント
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app